// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/pass2-generate-artifacts.js

export const SESSION_VALUES = [
  "TOKYO_SESSION",
  "LONDON_SESSION",
  "NEW_YORK_SESSION",
] as const;

export type Session = typeof SESSION_VALUES[number];

export const RISK_TIER_VALUES = [
  "NORMAL",
  "REDUCED",
  "PRESERVATION",
] as const;

export type RiskTier = typeof RISK_TIER_VALUES[number];

export const MACRO_BIAS_VALUES = [
  "BULLISH",
  "BEARISH",
  "RANGE",
] as const;

export type MacroBias = typeof MACRO_BIAS_VALUES[number];

export const MACRO_CURRENT_PHASE_VALUES = [
  "ACCUMULATION",
  "EXPANSION",
  "DISTRIBUTION",
] as const;

export type MacroCurrentPhase = typeof MACRO_CURRENT_PHASE_VALUES[number];

export const LIQUIDITY_TARGET_DIRECTION_VALUES = [
  "ABOVE",
  "BELOW",
  "RANGE_BOUNDARY",
] as const;

export type LiquidityTargetDirection = typeof LIQUIDITY_TARGET_DIRECTION_VALUES[number];

export const MID_STRUCTURE_SEQUENCE_VALUES = [
  "HH_HL",
  "LL_LH",
  "RANGE",
] as const;

export type MidStructureSequence = typeof MID_STRUCTURE_SEQUENCE_VALUES[number];

export const RECENT_STRUCTURAL_EVENT_VALUES = [
  "BOS",
  "CHOCH",
  "NONE",
] as const;

export type RecentStructuralEvent = typeof RECENT_STRUCTURAL_EVENT_VALUES[number];

export const MID_STRUCTURE_REGIME_VALUES = [
  "CLEAN_TREND",
  "WEAK_TREND",
  "CHOP",
] as const;

export type MidStructureRegime = typeof MID_STRUCTURE_REGIME_VALUES[number];

export const MID_STRUCTURE_RSI_STATE_VALUES = [
  "TRENDING",
  "DIVERGENCE",
  "NEUTRAL",
] as const;

export type MidStructureRsiState = typeof MID_STRUCTURE_RSI_STATE_VALUES[number];

export const MID_STRUCTURE_EMA_STATE_VALUES = [
  "STACKED",
  "STACKED_EXPANDING",
  "STACKED_COMPRESSING",
  "COMPRESSED",
  "FLAT",
] as const;

export type MidStructureEmaState = typeof MID_STRUCTURE_EMA_STATE_VALUES[number];

export const MID1M_ADXSTATE_STRENGTH_VALUES = [
  "STRONG",
  "WEAK",
] as const;

export type Mid1mAdxstateStrength = typeof MID1M_ADXSTATE_STRENGTH_VALUES[number];

export const MID1M_ADXSTATE_MOMENTUM_VALUES = [
  "RISING",
  "FALLING",
  "FLATTENING",
] as const;

export type Mid1mAdxstateMomentum = typeof MID1M_ADXSTATE_MOMENTUM_VALUES[number];

export const MID5M_ADXSTATE_STRENGTH_VALUES = [
  "STRONG",
  "WEAK",
] as const;

export type Mid5mAdxstateStrength = typeof MID5M_ADXSTATE_STRENGTH_VALUES[number];

export const MID5M_ADXSTATE_MOMENTUM_VALUES = [
  "RISING",
  "FALLING",
  "FLATTENING",
] as const;

export type Mid5mAdxstateMomentum = typeof MID5M_ADXSTATE_MOMENTUM_VALUES[number];

export const PRIMARY_STRATEGY_VALUES = [
  "TC1",
  "TC2",
  "TCL",
  "CH1",
  "SMOG",
  "G2",
  "35A",
] as const;

export type PrimaryStrategy = typeof PRIMARY_STRATEGY_VALUES[number];

export const ENTRY_TYPE_VALUES = [
  "MARKET",
  "LIMIT",
] as const;

export type EntryType = typeof ENTRY_TYPE_VALUES[number];

export const TRADE_DIRECTION_VALUES = [
  "LONG",
  "SHORT",
] as const;

export type TradeDirection = typeof TRADE_DIRECTION_VALUES[number];

export const PRIMARY_STOP_BASIS_VALUES = [
  "STRUCTURAL_INVALIDATION",
] as const;

export type PrimaryStopBasis = typeof PRIMARY_STOP_BASIS_VALUES[number];

export const SECONDARY_EXIT_LOGIC_VALUES = [
  "LIQUIDITY_BASED_TRAIL",
  "VOLATILITY_BUFFER",
  "TIME_BASED_EXIT",
  "CONFIRMATION_FAILURE",
] as const;

export type SecondaryExitLogic = typeof SECONDARY_EXIT_LOGIC_VALUES[number];

export const TRADE_MANAGEMENT_PLAN_VALUES = [
  "PARTIAL_PROFIT_AT_R",
  "MOVE_STOP_TO_BREAKEVEN_AT_R",
] as const;

export type TradeManagementPlan = typeof TRADE_MANAGEMENT_PLAN_VALUES[number];
