// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/pass2-generate-artifacts.js

import type { EntryType, LiquidityTargetDirection, MacroBias, MacroCurrentPhase, Mid1mAdxstateMomentum, Mid1mAdxstateStrength, Mid5mAdxstateMomentum, Mid5mAdxstateStrength, MidStructureEmaState, MidStructureRegime, MidStructureRsiState, MidStructureSequence, PrimaryStopBasis, PrimaryStrategy, RecentStructuralEvent, RiskTier, SecondaryExitLogic, Session, TradeDirection, TradeManagementPlan } from "../constants/enums";

export interface PersistedPrecheckRun {
  todayDateTime: string; // Records Trade Idea Creation Date
  session: Session; // TOKYO SESSION', 'LONDON SESSION', 'NEW YORK SESSION'
  asset: string; // Records the Asset ticker symbol
  riskTier: RiskTier; // NORMAL', 'REDUCED', 'PRESERVATION'
  macroClarityScore: number; // Total calculated score based on the responses in the Macro Section
  midStructureScore: number; // Total calculated score based on the responses in the Mid-Structure Section
  oneSentenceThesis: string; // A single sentence that is well thought out explaining the thesis behind the trade idea
  strategyFitScore: number; // Total calculated score based on the responses in the Strategy Fit Section
  tradeDirection: TradeDirection; // LONG', 'SHORT'
  entryPrice: number; // Trade idea entry price
  stopPrice: number; // trade idea stop loss price
  targetPrice: number; // trade idea target price
  plannedRR: number; // calculates the planned R:R based on the entry, stop, target price, and position size.
  positionSize: number; // calculated position size based on planned risk and entry and stop loss price
  tradeManagementPlan: TradeManagementPlan; // provides which choice of trading management plan this trade idea will take
  partialAtR: number; // at what point do you take partial profit based on a given positive R level
  moveStopToBreakEvenAtR: number; // at what point do you move stop loss to the break even point based on a given positive R level
  executionQualityScore: number; // Total calculated score based on the responses in the Execution Quality Section
  macroWeightedScore: number; // Calculated weighted score for Section 2
  midWeightedScore: number; // Calculated weighted score for Section 3
  strategyWeightedScore: number; // Calculated weighted score for Section 4
  executionWeightedScore: number; // Calculated weighted score for Section 5
  finalCompositeScore: number; // Calculated final composite score based on the aggregate of the 4each Section Weighted Scores
  blockingReasons: string; // provides a reason the trade is being blocked
  thresholdUsed: number; // final score minimum based on Risk Tier
  warnings: string; // Warning displayed based on which hard stop is triggered.
  hsDailyLossHit: boolean; // returns True/False if you have hit the daily loss limit based on your risk plan
  hsWeeklyLossHit: boolean; // returns True/False if you have hit the weekly loss limit based on your risk plan
  hsRiskViolation: boolean; // returns True/False if trade planned risk is more than the limit set based on the Risk Tier
  hsEmotionalTrade: boolean; // returns True/False if this trade is motivated by Revenge, Emotions, or a Sense of Urgency/FOMO
  hsNoLiquidityDrawIdentified: boolean; // returns True/False if you have identified a clear liquidity Draw
  hsMacroClarityLt7: boolean; // returns True/False if the analysis of the Macro Context (4h+) section score is greater than 7
  hsMicroNotAlignedMacro: boolean; // returns True/False if the Mid-Structure is aligned with the Macro Structure
  hsNoStructuralConfirmation: boolean; // returns True/False if there has been some form of Structural Confirmation of which direction the market is headed…with BOS or CHoCH
  hsStrategyNotClear: boolean; // returns True/False if the primary trade strategy is clearly declared in section 4
  hsThesisNotWrittenClearly: boolean; // returns True/False if the Thesis is written clearly
  hsRequiredStrategyRegimeNotPresent: boolean; // returns True/False if the market is showing the required regime for the chosen strategy is present
  hsChopContinuationStrategy: boolean; // returns True/False if the market is in a CHOPPY regime with a Continuation Strategy selected
  hsStopNotStructurallyBased: boolean; // returns True/False if the trade idea stop price is based on structural invalidation or not
  hsRRBelowStrategyMinimum: boolean; // returns True/False if the R:R is below the chosen strategy's minimum
  hsEntryChasingPrice: boolean; // returns True/False if the trade idea is trying to chase the price instead of being set and held
  hsPositionSizeViolatesRiskTierAllowance: boolean; // returns True/False if the trade idea position size violates the risk tier allowance
  hsTradeNotLogged: boolean; // returns True/False if the trade idea has been logged into the database
}

export interface PrecheckPayload {
  session: Session; // TOKYO SESSION', 'LONDON SESSION', 'NEW YORK SESSION'
  asset: string; // Records the Asset ticker symbol
  riskTier: RiskTier; // NORMAL', 'REDUCED', 'PRESERVATION'
  acctBalance: number; // saves current account balance for the trade
  plannedRisk: number; // planned risk percentage for given trade
  macroBias: MacroBias; // 'BULLISH', 'BEARISH', 'RANGE'
  macroCurrentPhase: MacroCurrentPhase; // 'ACCUMULATION', 'EXPANSION', 'DISTRIBUTION'
  keyHTFResistanceFrom: number; // lowest price point of the resistance zone
  keyHTFResistanceTo: number; // highest price point of the resistance zone
  keyHTFSupportFrom: number; // lowest price point of the resistance zone
  keyHTFSupportTo: number; // highest price point of the resistance zone
  macroLiquidityDraw: number; // price of different macro Liquidity Draw
  liquidityTargetDirection: LiquidityTargetDirection; // 'ABOVE', 'BELOW', 'RANGE_BOUNDARY'
  bullishMacroBiasInvalidationLevel: number; // price point of the point where the market will shift to a Bullish Bias if reached
  bearishMacroBiasInvalidationLevel: number; // price point of the point where the market will shift to a Bearish Bias if reached
  macroClarityScore: number; // Total calculated score based on the responses in the Macro Section
  midStructureSequence: MidStructureSequence; // 'HH_HL', 'LL_LH', 'RANGE'
  microMacroAlignment: boolean; // returns True/False if the Micro Structure is aligned with the Macro Bias
  recentStructuralEvent: RecentStructuralEvent; // 'BOS', 'CHOCH', 'NONE'
  liquiditySweepObserved: boolean; // returns True/False if a Liquidity Sweep is observed
  midStructureRegime: MidStructureRegime; // 'CLEAN_TREND', 'WEAK_TREND', 'CHOP'
  midStructureRsiState: MidStructureRsiState; // 'TRENDING', 'DIVERGENCE', 'NEUTRAL'
  midStructureEmaState: MidStructureEmaState; // 'STACKED', 'STACKED_EXPANDING', 'STACKED_COMPRESSING', 'COMPRESSED', 'FLAT'
  mid1mADXStateStrength: Mid1mAdxstateStrength; // 'STRONG (>20)', 'WEAK (<20)'
  mid1mADXStateMomentum: Mid1mAdxstateMomentum; // RISING', 'FALLING', 'FLATTENING'
  mid5mADXStateStrength: Mid5mAdxstateStrength; // 'STRONG (>20)', 'WEAK (<20)'
  mid5mADXStateMomentum: Mid5mAdxstateMomentum; // RISING', 'FALLING', 'FLATTENING'
  midStructureScore: number; // Total calculated score based on the responses in the Mid-Structure Section
  primaryStrategy: PrimaryStrategy; // 'TC2', 'TC1', 'TCL', 'CH1', 'SMOG', 'G2', '35A'
  oneSentenceThesis: string; // A single sentence that is well thought out explaining the thesis behind the trade idea
  strategyFitScore: number; // Total calculated score based on the responses in the Strategy Fit Section
  entryType: EntryType; // 'MARKET', 'LIMIT'
  tradeDirection: TradeDirection; // LONG', 'SHORT'
  entryPrice: number; // Trade idea entry price
  stopPrice: number; // trade idea stop loss price
  targetPrice: number; // trade idea target price
  plannedRR: number; // calculates the planned R:R based on the entry, stop, target price, and position size.
  positionSize: number; // calculated position size based on planned risk and entry and stop loss price
  primaryStopBasis: PrimaryStopBasis; // 'STRUCTURAL_INVALIDATION'
  secondaryExitLogic: SecondaryExitLogic; // 'LIQUIDITY_BASED_TRAIL', 'VOLATILITY_BUFFER', 'TIME_BASED_EXIT', 'CONFIRMATION_FAILURE'
  tradeManagementPlan: TradeManagementPlan; // provides which choice of trading management plan this trade idea will take
  partialAtR: number; // at what point do you take partial profit based on a given positive R level
  moveStopToBreakEvenAtR: number; // at what point do you move stop loss to the break even point based on a given positive R level
  executionQualityScore: number; // Total calculated score based on the responses in the Execution Quality Section
}

export interface WeightedScoreResult {
  macroWeightedScore: number; // Calculated weighted score for Section 2
  midWeightedScore: number; // Calculated weighted score for Section 3
  strategyWeightedScore: number; // Calculated weighted score for Section 4
  executionWeightedScore: number; // Calculated weighted score for Section 5
  finalCompositeScore: number; // Calculated final composite score based on the aggregate of the 4each Section Weighted Scores
}

export interface DecisionResult {
  finalCompositeScore: number; // Calculated final composite score based on the aggregate of the 4each Section Weighted Scores
  blockingReasons: string; // provides a reason the trade is being blocked
  thresholdUsed: number; // final score minimum based on Risk Tier
  warnings: string; // Warning displayed based on which hard stop is triggered.
  anyHardStopsTriggered: boolean; // returns True/False if there are any hard stops triggered throughout the different sections.
}

export interface HardStopEvaluationResult {
  section1Result: Record<string, unknown>; // result of function evaluateSection1HardStops
  section2Result: Record<string, unknown>; // result of function evaluateSection2HardStops
  section3Result: Record<string, unknown>; // result of function evaluateSection3HardStops
  section4Result: Record<string, unknown>; // result of function evaluateSection4HardStops
  section5Result: Record<string, unknown>; // result of function evaluateSection5HardStops
  hardStopResults: unknown; // Collects if there are Hard Stops from each section
  anyHardStopsTriggered: boolean; // returns True/False if there are any hard stops triggered throughout the different sections.
}
